from ClasePila import ClasePila
pila=ClasePila()
print(pila.Empty())
pila.insertarElemento("hola")
pila.insertarElemento("soy")
pila.insertarElemento("anderson")
pila.insertarElemento("el")
pila.insertarElemento("programador")
pila.leerPila()
pila.eliminarElemento()
pila.leerPila()
print(pila.Empty())
